apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZCRENDQXV5Z0F3SUJBZ0lCS2pBTkJna3Foa2lHOXcwQkFRc0ZBREFSTVE4d0RRWURWUVFEREFZd2RIbzAKZHpnd0hoY05NalV3TVRFd01EYzBPRFF3V2hjTk5EQXdNVEEzTURjME9EUXdXakFSTVE4d0RRWURWUVFEREFZdwpkSG8wZHpnd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUUNOT2VVejlaeFdwdmY5CjE3WFl2OGd0QmdVMk5IYXo1aHcxYmpZdW5IMjN1V00zSi9JK0FpNm1SMllnS2JUU01wNHl0VFdreEE4VGZzTWMKdUREVU5Dc1FvS3NLS3U2WmFCbFNRNUpKRDl6L0FwZXNlWjZtNjk1N1RVRFlqWW1PaEcvWXpPUEl4STkxM2pETAoySVRscG5BMTFzd3RFVzYzcnFkUmtjNENhWnpjM1ljRnh3TVl4bFZKME5QS09PNVJWQ20xQUovOFlDRm15aEFqClREczI4SW4xcDZsdWlFYWpwWmtUZXFiOFJyR1BLUWFIT3NJWTZnSkdORUpSYStUVExuNzBVN0FKSmp5eS9SYm0KY05reERLUHhCS0RkOWpqSlJZemJyUXZPQVNmUis2ZVNRa1Vpb2V3dGtTT0FQaGlHbVJadmVYQlpKcnRMWHRmaAp5YW9kV3MzNnlxbnV4bDFtUWtnZmFCT3pSdkNZU1c0M0lycG1FUEc4SGpqdHpicTZSZ2ZqUG1MbmpZMlV4aGN5CkRPUFRDVmhsR1BmcWwvclcvcWY2Q2N5RkdteVp5STBsM1BiRmljdlV3OGxpa1VuVUNBSFgwTzl3cVo3UDBrZFkKWStFZ3FnOXJVa1pFeExGMXZYaHJ4V2ZJQjdRZTA5WW1ZeWk1b2dCYUdXUmxSK1dqL0EvZEgxUk5OcmtUNmtqbgpCcDZhOGM4WFAwSHVnRGNRWUg3VEk3M0xTcnU3SzArYnQ5RC9nU2d3RkJvMkZiU2plcDlIQmpQbzFMaHg4aE5TCnhVbTNiN0UxOVovdEMyN3dEa29MTEdSaHF6b0RPdkZKYmE4S0ljUVFRVUZ6bzduM0ZHMHlxckZRYSsrdVoxcnYKYlhuczJESlF3djJSQ3hVUExpVDhJYlp4djhEdnl3SURBUUFCbzJjd1pUQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQTRHQTFVZER3RUIvd1FFQXdJQkJqQWRCZ05WSFE0RUZnUVVFVXhqVkJUdWkvK3B1cEcydmxKa3ROOG9Ga2N3Ckl3WURWUjBqQkJ3d0dxRVZwQk13RVRFUE1BMEdBMVVFQXd3R01IUjZOSGM0Z2dFcU1BMEdDU3FHU0liM0RRRUIKQ3dVQUE0SUNBUUE5UmhGc2dBZTB5NE1QejNDT3hLRUdaaGo0WFE5TXd1blFQd2FpQzl4eHZRRk1yY21pK1NaTQpiMWV3OGhRQlpyUmorY3FVd3JGdGRmMEZNOUdyVnZGanVVRDgwbDN5YWExUHpmelhoRThMZ3JvYWo5T05BaXNCCmhXSEdhUTluT2dMa01mTWt0QmN5NTdmeVBERUFNRU5ZTnRkdzNHbXhrdXZpVlgrR21hYk51TU9sZlhTRmZGNlQKZ0dQWEY4OXAyYWtidXNEbjhPNkQrWVBQakh1eUU5YlorZmZ0YUVGcHFydW1OWk9rZUlSYURLWkt4UlIwcVRrZwpzWkV1eHQ5MUZad0VMd1hUT2pudEdMQzFBYys0MTFiTDZuUG5CYUFUdENsekp4VUloNFh4RnprSk9JdkVheTVOCkIvZXV6ZWMvbnBxNDh2Q2hlYmdOZWZhZDZ3aXlyZ0s2Y3NyaERBeHdGNGlzcEhJWlFTMGNUbDNCS1p3RDdFSmIKRVVMNmNBd2FpVGdwSjlLSHNqaEp2TExpVHpsL1RmMVJBd0IrNEJNK3ZUQkgrWHVNWDJYL1hNa084d1FuVVdqRwpDTHJSMGQ2NTdkblhVZmlwbHcrSEN6K0xucStOeFJhWTBwMmZuVGc0NTZPQXF4WW1jeURzdkNjZWhaMkVhaGpRCnd6dGpYSTJoc2FaajV1UzhjU2RXbDlValRFdnBuQmNnV0lGUTNPcGRUcU9mZXBqdSs1enVpZUdPM3BqZHV3UC8KdmJqMmQxdEMxN2hmZVA3VWhJL3VOamZ6SDRlcnJhdlNoVDh1aTBtalgrYWVHU0hiMEEzRklTTzk3NWtNaUkxZQpBK0NjTFdqSGQ2aDN4TmUycEFpdSsrYTlZV1Z4SVpOQk9mOGRJbnBmSDlFVG9qWnpKZk1PZEE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      server: https://0tz4w8.c1.gra9.k8s.ovh.net
    name: pwcv4-kube-pegasus-oidc
contexts:
  - context:
      cluster: pwcv4-kube-pegasus-oidc
      user: oidc
    name: pwcv4-kube-pegasus-oidc
current-context: pwcv4-kube-pegasus-oidc
kind: Config
preferences: {}
users:
  - name: oidc
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - oidc-login
          - get-token
          - --oidc-issuer-url=https://keycloak.pwcv4.com/realms/master
          - --oidc-client-id=hps-k8s-default
          - --oidc-client-secret=IIF4F15mgzC1QwfElUDcwXE6l5Iy52sN
        command: kubectl
        env: null
        provideClusterInfo: false